# Generated by Django 5.2.5 on 2025-09-05 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visitors", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="visitor",
            name="is_rescheduled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="visitor",
            name="original_visit_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="visitor",
            name="original_visit_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
