# Generated by Django 5.2.5 on 2025-09-08 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "visitors",
            "0002_visitor_is_rescheduled_visitor_original_visit_date_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="visitor",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("verified", "Verified"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                    ("expired", "Expired"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
