# Generated by Django 5.2.5 on 2025-10-08 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visitors", "0003_alter_visitor_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="visitor",
            name="visitor_category",
            field=models.CharField(
                choices=[("industry", "Industry"), ("academic", "Academic")],
                default="industry",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="visitor",
            name="visitor_type",
            field=models.CharField(
                choices=[("emp", "Employee"), ("student", "Student")],
                default="emp",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="visitor",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("business_meeting", "Business Meeting"),
                    ("interview", "Interview"),
                    ("delivery", "Delivery"),
                    ("maintenance", "Maintenance"),
                    ("training", "Training"),
                    ("i_factory_visit", "iFactory Visit"),
                    ("i_factory_training", "iFactory Training"),
                    ("other", "Other"),
                ],
                max_length=20,
            ),
        ),
    ]
