# Generated by Django 4.2.7 on 2025-12-01 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("visitors", "0002_update_visitor_choices"),
        ("visitors", "0004_visitor_visitor_category_visitor_visitor_type_and_more"),
    ]

    operations = []
