# Generated by Django 4.2.7 on 2025-12-06 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("visitors", "0005_merge_20251201_1204"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visitor",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="visitors.department",
            ),
        ),
        migrations.AlterField(
            model_name="visitor",
            name="visitor_category",
            field=models.CharField(
                choices=[
                    ("government", "Government"),
                    ("academic", "Academic"),
                    ("industry", "Industry"),
                    ("other", "Other"),
                ],
                default="industry",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="visitor",
            name="visitor_type",
            field=models.CharField(
                choices=[("professional", "Professional"), ("student", "Student")],
                default="professional",
                max_length=15,
            ),
        ),
    ]
