# Generated by Django 4.2.7 on 2026-01-08 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visitors", "0006_alter_visitor_department_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visitor",
            name="visitor_category",
            field=models.CharField(
                choices=[
                    ("government", "Government"),
                    ("academic", "Academic"),
                    ("industry", "Industry"),
                    ("other", "Other"),
                ],
                default="industry",
                max_length=20,
            ),
        ),
    ]
